stages:
  preprocess_data:
    cmd: python -m scripts.preprocess_data
    deps:
    - scripts/preprocess_data.py
    params:
    - datapath
    - timedelta
    outs:
    - data/preprocessed_dataframe.pkl

  calculate_event_graph_weights:
    cmd: python -m scripts.create_event_graph
    deps:
    - scripts/create_event_graph.py
    - data/preprocessed_dataframe.pkl
    params:
    - timedelta
    - data_ratio
    outs:
    - data/w_path_dict.pkl
    - data/w_co_dict.pkl
    - data/event_to_nodes.pkl

  sample_neighbourhoods:
    cmd: python -m scripts.sample_neighbourhoods
    deps:
    - data/w_path_dict.pkl
    - data/w_co_dict.pkl
    - data/event_to_nodes.pkl
    - scripts/sample_neighbourhoods.py
    params:
    - sampling.alpha
    - sampling.nb
    - sampling.s
    outs:
    - data/sampled_neighbourhoods.pkl
    
  apply_skipgram:
    cmd: python -m scripts.apply_skipgram
    deps:
    - data/sampled_neighbourhoods.pkl
    params:
    - skipgram.epochs
    - skipgram.min_count
    - skipgram.vector_size
    - skipgram.window
    outs:
    - data/embeddings.pkl

  visualize:
    cmd: python -m scripts.visualize
    deps:
    - data/embeddings.pkl
