stages:
  preprocess_data:
    cmd: PYTHONPATH=. python3 scripts/preprocess_data.py
    deps:
    - scripts/preprocess_data.py
    params:
    - datapath
    - timedelta
    outs:
    - data/preprocessed_dataframe.pkl

  calculate_event_graph_weights:
    cmd: PYTHONPATH=. python3 scripts/create_event_graph.py
    deps:
      - scripts/create_event_graph.py
    params:
      - timedelta
      - data_ratio
    outs:
      - data/w_path_dict.pkl
      - data/w_co_dict.pkl
      - data/event_to_nodes.pkl
